language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

install:
  - composer install

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
