imports:
  - { resource: 'config.xml' }

parameters:
  - jane: poep


services:

  flexsounds.test.a:
    class: 'Flexsounds\Slim\ContainerBuilder\Dummy'
    arguments:
      - '@settings'

  flexsounds.test.b:
      class: 'Flexsounds\Slim\ContainerBuilder\Dummy'
      arguments:
        - '@flexsounds.test.a'

  fiets:
      class: 'Flexsounds\Slim\ContainerBuilder\Dummy'
      arguments:
        - '@flexsounds.test.b'