#imports:
#  - { resource: 'config.xml' }

parameters:
  - jane: poep


services:
  oepsie:
    class: 'Flexsounds\Slim\ContainerBuilder\Dummy'
    arguments:
      - 'fietsje'
  fiets:
    class: 'Flexsounds\Slim\ContainerBuilder\Dummy'
    arguments:
      - '@oepsie'